version: '3.8'

services:
  # FastAPI Application
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /code/app
    volumes:
      - ./app:/code/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    # Allows container to talk to host machine (for Ollama)
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Celery Worker
  worker:
    build: .
    command: celery -A app.celery_worker.celery_app worker --loglevel=info
    volumes:
      - ./app:/code/app
    env_file:
      - .env
    depends_on:
      - redis
    # Allows container to talk to host machine (for Ollama)
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Redis Broker & Backend
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"